# Generated by Django 3.2.4 on 2021-07-27 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchdb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=30)),
                ('shopname', models.CharField(max_length=100)),
                ('shopaddress', models.CharField(max_length=500)),
                ('shopcontact', models.CharField(max_length=12)),
                ('shopimage', models.ImageField(upload_to='searchdb/')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
