# Generated by Django 3.2.4 on 2021-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=5000)),
                ('status', models.CharField(default='NOT RESPONDED', max_length=20)),
            ],
        ),
    ]
