# Generated by Django 3.2.4 on 2021-07-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userquery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='status',
            field=models.CharField(default='NOT RESPONDED', max_length=50),
        ),
    ]
