# Generated by Django 3.2.4 on 2021-06-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userid',
            new_name='user',
        ),
    ]
