# Generated by Django 3.2.4 on 2021-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_rename_userid_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='securityanswer',
            field=models.CharField(max_length=100),
        ),
    ]
